### ISSUE TITLE
Issues with comments

### ISSUE THREAD

**Issue by xatavian** [eerimoq/cantools#13] opened 2017-11-30 11:06 UTC
Hello,

I have a dbc file which cannot be parsed by `cantools`. I looked at `pyparsing` Exception and it looks like the problem comes from one of the comments. 

The error can be seen in the following dbc string:

```
VERSION "TEST"
CM_ "";
```

This crashes and `pyparsing` outputs `Expected end of text (at char 15), (line:2, col:1)`

I also tried with : 
```
VERSION "TEST"
BS_: 
```
And it worked fine.

Best regards,

**Comment by eerimoq** [comment] 2017-11-30 20:12
Hi,

any possibility of posting the entire DBC-file? It would be very helpful to test a fix.

**Comment by xatavian** [comment] 2017-12-03 15:17
Hi,

I'm sorry but i'm not allowed to share the dbc file. I can try to make a pull request but i don't know how pyparsing works so i'd havet to take a look at that :) !

Best regards,

**Comment by eerimoq** [comment] 2017-12-03 16:09
I implemented a fix in 1d6247d9dc1a8b5b8fbc9d2b16be79aa7f37a676.

Let me know if it works or not.

**Comment by vargabalint92** [comment] 2017-12-06 15:34
Hi

unfortunately i have still some problems with comments.

**Comment by eerimoq** [comment] 2017-12-06 22:04
Closing issue since a detailed description of the problem is missing.

**Closed by eerimoq** 2017-12-06 22:04 UTC
